;; -*- coding: utf-8; lexical-binding: t; -*-
;; ";; " from site-lisp dir, it's removed
;;(autoload 'auto-save-enable "auto-save" "" t)
(autoload 'counsel-etags-find-tag-at-point "counsel-etags" "" t nil)
(autoload 'counsel-etags-list-tag-in-current-file "counsel-etags" "" t nil)
(autoload 'counsel-etags-push-marker-stack "counsel-etags" "" t nil)
(autoload 'counsel-etags-scan-code "counsel-etags" "" t nil)
(autoload 'counsel-etags-filename-p "counsel-etags" "" t nil)
(autoload 'counsel-etags-grep "counsel-etags" "" t nil)
(autoload 'counsel-etags-recent-tag "counsel-etags" "" t nil)
(autoload 'magit-commit-popup "magit" "")
(autoload 'buf-move-left "buffer-move" "move buffer" t)
(autoload 'buf-move-right "buffer-move" "move buffer" t)
(autoload 'buf-move-up "buffer-move" "move buffer" t)
(autoload 'buf-move-down "buffer-move" "move buffer" t)
;;(autoload 'global-git-gutter-mode "git-gutter" "" t)
(autoload 'keyfreq-mode "keyfreq" "" t)
(autoload 'keyfreq-autosave-mode "keyfreq" "" t)
;;(autoload 'origami-mode "origami" "" t)
(autoload 'workgroups-mode "workgroups2" nil t)
(autoload 'wg-create-workgroup "workgroups2" nil t)
(autoload 'wg-open-workgroup "workgroups2" nil t)
(autoload 'which-function "which-func")
;;(autoload 'vc-msg-show "vc-msg" "")
(autoload 'snippet-mode "yasnippet" "")
(autoload 'xclip-set-selection "xclip" "" t)
(autoload 'xclip-get-selection "xclip" "" t)

(provide 'init-autoload)
